/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface AYLWhiteListInterface extends utils.Interface {
  functions: {
    "addToWhiteList()": FunctionFragment;
    "getWhitelistedAddresses()": FunctionFragment;
    "numberOfWhitelistedAddresses()": FunctionFragment;
    "whitelistedAddress(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addToWhiteList"
      | "getWhitelistedAddresses"
      | "numberOfWhitelistedAddresses"
      | "whitelistedAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addToWhiteList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWhitelistedAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfWhitelistedAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistedAddress",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addToWhiteList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWhitelistedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numberOfWhitelistedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistedAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export interface AYLWhiteList extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AYLWhiteListInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addToWhiteList(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getWhitelistedAddresses(overrides?: CallOverrides): Promise<[string[]]>;

    numberOfWhitelistedAddresses(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    whitelistedAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  addToWhiteList(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getWhitelistedAddresses(overrides?: CallOverrides): Promise<string[]>;

  numberOfWhitelistedAddresses(overrides?: CallOverrides): Promise<BigNumber>;

  whitelistedAddress(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    addToWhiteList(overrides?: CallOverrides): Promise<void>;

    getWhitelistedAddresses(overrides?: CallOverrides): Promise<string[]>;

    numberOfWhitelistedAddresses(overrides?: CallOverrides): Promise<BigNumber>;

    whitelistedAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    addToWhiteList(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getWhitelistedAddresses(overrides?: CallOverrides): Promise<BigNumber>;

    numberOfWhitelistedAddresses(overrides?: CallOverrides): Promise<BigNumber>;

    whitelistedAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addToWhiteList(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getWhitelistedAddresses(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numberOfWhitelistedAddresses(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    whitelistedAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
